diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index 2a2f2e26757cc..61daa201a826a 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -2021,6 +2021,32 @@ enum HistogramValue {
   AUTOFILLPRIVATE_TOGGLEAUTOFILLAIREAUTHREQUIREMENT = 1958,
   AUTOFILLPRIVATE_GETREQUIREDATTRIBUTETYPESFORENTITYTYPENAME = 1959,
   PDFVIEWERPRIVATE_GLICSUMMARIZE = 1960,
+  // BrowserOS: extension function histogram values
+  BROWSER_OS_GETACCESSIBILITYTREE = 1961,
+  BROWSER_OS_GETINTERACTIVESNAPSHOT = 1962,
+  BROWSER_OS_CLICK = 1963,
+  BROWSER_OS_INPUTTEXT = 1964,
+  BROWSER_OS_CLEAR = 1965,
+  BROWSER_OS_GETPAGELOADSTATUS = 1966,
+  BROWSER_OS_SCROLLUP = 1967,
+  BROWSER_OS_SCROLLDOWN = 1968,
+  BROWSER_OS_SCROLLTONODE = 1969,
+  BROWSER_OS_SENDKEYS = 1970,
+  BROWSER_OS_GETPAGESTRUCTURE = 1971,
+  BROWSER_OS_CAPTURESCREENSHOT = 1972,
+  BROWSER_OS_GETSNAPSHOT = 1973,
+  BROWSER_OS_GETPREF = 1974,
+  BROWSER_OS_SETPREF = 1975,
+  BROWSER_OS_GETALLPREFS = 1976,
+  BROWSER_OS_LOGMETRIC = 1977,
+  BROWSER_OS_GETVERSIONNUMBER = 1978,
+  BROWSER_OS_EXECUTEJAVASCRIPT = 1979,
+  BROWSER_OS_CLICKCOORDINATES = 1980,
+  BROWSER_OS_TYPEATCOORDINATES = 1981,
+  SIDEPANEL_BROWSEROSTOGGLE = 1982,
+  SIDEPANEL_BROWSEROSISOPEN = 1983,
+  BROWSER_OS_GETBROWSEROSVERSIONNUMBER = 1984,
+  BROWSER_OS_CHOOSEPATH = 1985,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
